src/Entity/NavigationBlock.php
<?php

declare(strict_types=1);

namespace Drupal\navigation\Entity;

use Drupal\Core\Condition\ConditionPluginCollection;
use Drupal\Core\Config\Entity\ConfigEntityBase;
use Drupal\Core\Config\Entity\ConfigEntityInterface;
use Drupal\Core\Entity\EntityWithPluginCollectionInterface;
use Drupal\navigation\NavigationBlockInterface;
use Drupal\navigation\NavigationBlockPluginCollection;

/**
 * Defines the navigation block entity type.
 *
 * @ConfigEntityType(
 *   id = "navigation_block",
 *   label = @Translation("Navigation block"),
 *   label_collection = @Translation("Navigation blocks"),
 *   label_singular = @Translation("navigation block"),
 *   label_plural = @Translation("navigation blocks"),
 *   label_count = @PluralTranslation(
 *     singular = "@count navigation block",
 *     plural = "@count navigation blocks",
 *   ),
 *   handlers = {
 *     "access" = "Drupal\navigation\NavigationBlockAccessControlHandler",
 *     "view_builder" = "Drupal\navigation\NavigationBlockViewBuilder",
 *     "list_builder" = "Drupal\navigation\NavigationBlockListBuilder",
 *     "form" = {
 *       "default" = "Drupal\navigation\Form\NavigationBlockForm",
 *       "delete" = "Drupal\navigation\Form\NavigationBlockDeleteForm",
 *     },
 *   },
 *   admin_permission = "administer navigation_block",
 *   entity_keys = {
 *     "id" = "id",
 *     "status" = "status",
 *   },
 *   links = {
 *     "delete-form" = "/admin/config/user-interface/navigation-block/manage/{navigation_block}/delete",
 *     "edit-form" = "/admin/config/user-interface/navigation-block/manage/{navigation_block}",
 *     "enable" = "/admin/config/user-interface/navigation-block/manage/{navigation_block}/enable",
 *     "disable" = "/admin/config/user-interface/navigation-block/manage/{navigation_block}/disable",
 *   },
 *   config_export = {
 *     "id",
 *     "region",
 *     "weight",
 *     "provider",
 *     "plugin",
 *     "settings",
 *     "visibility",
 *   },
 * )
 */
class NavigationBlock extends ConfigEntityBase implements NavigationBlockInterface, EntityWithPluginCollectionInterface {

  /**
   * The ID of the navigation_block.
   *
   * @var string
   */
  protected string $id;

  /**
   * The plugin instance settings.
   *
   * @var array
   */
  protected array $settings = [];

  /**
   * The region this navigation_block is placed in.
   *
   * @var string|null
   */
  protected ?string $region = NULL;

  /**
   * The navigation_block weight.
   *
   * @var int
   */
  protected int $weight;

  /**
   * The plugin instance ID.
   *
   * @var string
   */
  protected string $plugin;

  /**
   * The visibility settings for this navigation_block.
   *
   * @var array
   */
  protected array $visibility = [];

  /**
   * The plugin collection that holds the navigation_block plugin.
   *
   * @var \Drupal\block\BlockPluginCollection
   */
  protected $pluginCollection;

  /**
   * The available contexts for this block and its visibility conditions.
   *
   * @var array
   */
  protected $contexts = [];

  /**
   * The visibility collection.
   *
   * @var \Drupal\Core\Condition\ConditionPluginCollection
   */
  protected $visibilityCollection;

  /**
   * The condition plugin manager.
   *
   * @var \Drupal\Core\Executable\ExecutableManagerInterface
   */
  protected $conditionPluginManager;

  /**
   * The theme that includes the block plugin for this entity.
   *
   * @var string
   */
  protected $theme;

  /**
   * {@inheritdoc}
   */
  public function getPlugin() {
    return $this->getPluginCollection()->get($this->plugin);
  }

  /**
   * Encapsulates the creation of the navigation_block's LazyPluginCollection.
   *
   * @return \Drupal\Component\Plugin\LazyPluginCollection
   *   The navigation_block's plugin collection.
   */
  protected function getPluginCollection() {
    if (!$this->pluginCollection) {
      $this->pluginCollection = new NavigationBlockPluginCollection(\Drupal::service('plugin.manager.navigation_block'), $this->plugin, $this->get('settings'), $this->id());
    }
    return $this->pluginCollection;
  }

  /**
   * {@inheritdoc}
   */
  public function getPluginCollections() {
    return [
      'settings' => $this->getPluginCollection(),
      'visibility' => $this->getVisibilityConditions(),
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getPluginId() {
    return $this->plugin;
  }

  /**
   * {@inheritdoc}
   */
  public function getRegion() {
    return $this->region;
  }

  /**
   * {@inheritdoc}
   */
  public function getWeight() {
    return $this->weight;
  }

  /**
   * {@inheritdoc}
   */
  public function label() {
    $settings = $this->get('settings');
    if ($settings['label']) {
      return $settings['label'];
    }
    else {
      $definition = $this->getPlugin()->getPluginDefinition();
      return $definition['admin_label'];
    }
  }

  /**
   * Sort helper.
   *
   * Sorts active navigation_blocks by weight; sorts inactive
   * navigation_blocks by name.
   */
  public static function sort(ConfigEntityInterface $a, ConfigEntityInterface $b) {
    // Separate enabled from disabled.
    $status = (int) $b->status() - (int) $a->status();
    if ($status !== 0) {
      return $status;
    }

    // Sort by weight.
    $weight = $a->getWeight() - $b->getWeight();
    if ($weight) {
      return $weight;
    }

    // Sort by label.
    return strcmp($a->label(), $b->label());
  }

  /**
   * {@inheritdoc}
   */
  public function getVisibility() {
    return $this->getVisibilityConditions()->getConfiguration();
  }

  /**
   * {@inheritdoc}
   */
  public function setVisibilityConfig($instance_id, array $configuration) {
    $conditions = $this->getVisibilityConditions();
    if (!$conditions->has($instance_id)) {
      $configuration['id'] = $instance_id;
      $conditions->addInstanceId($instance_id, $configuration);
    }
    else {
      $conditions->setInstanceConfiguration($instance_id, $configuration);
    }
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function getVisibilityConditions() {
    if (!isset($this->visibilityCollection)) {
      $this->visibilityCollection = new ConditionPluginCollection($this->conditionPluginManager(), $this->get('visibility'));
    }
    return $this->visibilityCollection;
  }

  /**
   * {@inheritdoc}
   */
  public function getVisibilityCondition($instance_id) {
    return $this->getVisibilityConditions()->get($instance_id);
  }

  /**
   * Gets the condition plugin manager.
   *
   * @return \Drupal\Core\Executable\ExecutableManagerInterface
   *   The condition plugin manager.
   */
  protected function conditionPluginManager() {
    if (!isset($this->conditionPluginManager)) {
      $this->conditionPluginManager = \Drupal::service('plugin.manager.condition');
    }
    return $this->conditionPluginManager;
  }

  /**
   * {@inheritdoc}
   */
  public function setRegion($region) {
    $this->region = $region;
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function setWeight($weight) {
    $this->weight = $weight;
    return $this;
  }

}

templates/logo.svg.twig
<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 32 32" role="img" aria-label="{{ label }}">
  <rect fill="{{ bg_color|default('#347efe') }}" width="32" height="32" rx="8"/>
  <path fill="{{ fg_color|default('#fff') }}" d="M19,10.3C17.67,9,16.38,7.68,16,6.23,15.62,7.67,14.33,9,13,10.3c-2,2-4.31,4.31-4.31,7.74a7.32,7.32,0,0,0,14.64,0C23.32,14.61,21,12.32,19,10.3Zm-7.22,9.44c-.45,0-2.11-2.87,1-5.91l2,2.22a.18.18,0,0,1,0,.25h0A19.3,19.3,0,0,0,12,19.6C11.92,19.75,11.83,19.74,11.79,19.74ZM16,23.51A2.52,2.52,0,0,1,13.48,21a2.56,2.56,0,0,1,.63-1.66c.45-.56,1.89-2.12,1.89-2.12s1.41,1.59,1.89,2.11A2.5,2.5,0,0,1,18.52,21,2.52,2.52,0,0,1,16,23.51Zm4.82-4.09c-.06.12-.18.32-.35.33s-.32-.14-.55-.47c-.48-.71-4.67-5.09-5.46-5.94s-.09-1.27.18-1.55L16,10.44a35.72,35.72,0,0,1,4.25,4.8A4.5,4.5,0,0,1,20.82,19.42Z"/>
</svg>

templates/menu-region--footer.html.twig
<div class="admin-toolbar__item">
  <h4 id="{{ menu_heading_id }}" class="toolbar-block__title visually-hidden focusable">{{ title }}</h4>
  <ul class="toolbar-block__list">
    {% if help %}
      <li class="toolbar-block__list-item">
        {% include '@navigation/toolbar-button.html.twig' with {
          attributes: create_attribute({ 'href': path('help.main'), 'data-drupal-tooltip': 'Help'|t, 'data-drupal-tooltip-class': 'admin-toolbar__tooltip' }),
          icon: 'help',
          html_tag: 'a',
          text: 'Help'|t,
          extra_classes: 'toolbar-button--collapsible',
        } only %}
      </li>
    {% endif %}
    <li id="admin-toolbar-user-menu" class="toolbar-block__list-item toolbar-block__list-item--user toolbar-popover" data-toolbar-popover>
      {% include '@navigation/toolbar-button.html.twig' with {
        action: true,
        attributes: create_attribute({'aria-expanded': 'false', 'aria-controls': 'admin-toolbar-user-menu', 'data-toolbar-popover-control': true}),
        icon:  menu_name|clean_class,
        text: title,
        extra_classes: 'toolbar-button--expand--side toolbar-button--collapsible toolbar-popover__control',
        has_safe_triangle: TRUE,
      } only %}
      <div class="toolbar-popover__wrapper" data-toolbar-popover-wrapper>
        <span class="toolbar-popover__header toolbar-button toolbar-button--large toolbar-button--non-interactive">{{ title }}</span>
        <ul class="toolbar-menu toolbar-popover__menu">
          {% for item in items %}
            <li class="toolbar-menu__item toolbar-menu__item--level-1">
              <a
                href="{{ item.url }}"
                class="toolbar-button"
              >{{ item.title }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </li>
  </ul>
</div>

templates/navigation-block.html.twig
{#
/**
 * @file
 * Default theme implementation to display a navigation_block.
 *
 * Available variables:
 * - plugin_id: The ID of the navigation_block implementation.
 * - label: The configured label of the navigation_block if visible.
 * - configuration: A list of the navigation_block's configuration values.
 *   - label: The configured label for the navigation_block.
 *   - label_display: The display settings for the label.
 *   - provider: The module or other provider that provided this
       navigation_block plugin.
 *   - Navigation block plugin specific settings will also be stored here.
 * - content: The content of this navigation_block.
 * - attributes: array of HTML attributes populated by modules, intended to
 *   be added to the main container tag of this template.
 *   - id: A valid HTML ID and guaranteed unique.
 * - title_attributes: Same as attributes, except applied to the main title
 *   tag that appears in the template.
 * - title_prefix: Additional output populated by modules, intended to be
 *   displayed in front of the main title tag that appears in the template.
 * - title_suffix: Additional output populated by modules, intended to be
 *   displayed after the main title tag that appears in the template.
 *
 * @see template_preprocess_navigation_block()
 *
 * @ingroup themeable
 */
#}
<div{{ attributes.addClass('toolbar-block') }}>
  {{ title_prefix }}
  {% if label %}
    <h2{{ title_attributes.addClass('toolbar-block__title').setAttribute('data-drupal-tooltip', label).setAttribute('data-drupal-tooltip-class', 'toolbar-block__title-tooltip') }}>{{ label }}</h2>
  {% endif %}
  {{ title_suffix }}
  {% block content %}
    {{ content }}
  {% endblock %}
</div>

templates/navigation-menu.html.twig
{% import _self as menus %}
{% set menu_heading_id = 'menu--' ~ menu_name|clean_unique_id %}
<div class="admin-toolbar__item">
  <h4 id="{{ menu_heading_id }}" class="toolbar-block__title visually-hidden focusable">{{ title }}</h4>
  <ul class="toolbar-block__list" aria-labelledby="{{ menu_heading_id }}">
    {{ menus.menu_items(items, attributes, 0) }}
  </ul>
</div>

{% macro menu_items(items, attributes, menu_level) %}
  {% for item in items %}
    {% set item_id = ('navigation-link--' ~ item.original_link.pluginId)|clean_unique_id %}
    {% if menu_level == 0 %}
      {% if item.below is empty  %}
        <li id="{{ item_id }}" class="toolbar-block__list-item">
          {% include '@navigation/toolbar-button.html.twig' with {
            attributes: create_attribute({ 'href': item.url|render, 'data-drupal-tooltip': item.title, 'data-drupal-tooltip-class': 'admin-toolbar__tooltip' }),
            icon: item.class|clean_class,
            html_tag: 'a',
            text: item.title,
            extra_classes: 'toolbar-button--collapsible',
          } only %}
        </li>
      {% else %}
        <li id="{{ item_id }}" class="toolbar-block__list-item toolbar-popover" data-toolbar-popover>
          {% include '@navigation/toolbar-button.html.twig' with {
            action: true,
            attributes: create_attribute({'aria-expanded': 'false', 'aria-controls': item_id, 'data-toolbar-popover-control': true}),
            icon: item.class|clean_class,
            text: item.title,
            extra_classes: 'toolbar-button--expand--side toolbar-button--collapsible toolbar-popover__control',
            has_safe_triangle: TRUE,
          } only %}
          <div class="toolbar-popover__wrapper" data-toolbar-popover-wrapper inert>
            {% if item.url %}
              {{ link(item.title, item.url, create_attribute({'class': ['toolbar-popover__header', 'toolbar-button', 'toolbar-button--large']})) }}
            {% else %}
              <span class="toolbar-popover__header toolbar-button toolbar-button--large toolbar-button--non-interactive">{{ item.title }}</span>
            {% endif %}
            <ul class="toolbar-menu toolbar-popover__menu">
              {{ menus.menu_items(item.below, attributes, 1) }}
            </ul>
          </div>
        </li>
      {% endif %}

    {% elseif menu_level == 1 %}
      <li class="toolbar-menu__item toolbar-menu__item--level-{{ menu_level }}">
        {% if item.below is empty  %}
          <a
            href="{{ item.url }}"
            class="toolbar-button"
            data-index-text="{{ item.title|first|lower }}"
          >{{ item.title }}</a>
        {% else %}
          <button
            class="toolbar-button toolbar-button--expand--down"
            data-toolbar-menu-trigger="{{ menu_level }}"
            aria-expanded="false"
            data-index-text="{{ item.title|first|lower }}"
          >
            <span class="toolbar-menu__link-action visually-hidden">{{ 'Extend'|t }}</span>
            <span class="toolbar-menu__link-title">{{ item.title }}</span>
          </button>
          <ul class="toolbar-menu toolbar-menu--level-{{ menu_level + 1 }}" inert>
            {{ menus.menu_items(item.below, attributes, menu_level + 1) }}
          </ul>
        {% endif %}
      </li>
    {% else %}
      <li class="toolbar-menu__item toolbar-menu__item--level-{{ menu_level }}">
        {% if item.below is empty  %}
          <a
            href="{{ item.url }}"
            class="toolbar-menu__link toolbar-menu__link--{{ menu_level }}"
            data-index-text="{{ item.title|first|lower }}"
          >{{ item.title }}</a>
        {% else %}
          <button
            class="toolbar-menu__link toolbar-menu__link--{{ menu_level }}"
            data-toolbar-menu-trigger="{{ menu_level }}"
            aria-expanded="false"
            data-index-text="{{ item.title|first|lower }}"
          >
            <span class="toolbar-menu__link-action visually-hidden">{{ 'Extend'|t }}</span>
            <span class="toolbar-menu__link-title">{{ item.title }}</span>
          </button>
          <ul class="toolbar-menu toolbar-menu--level-{{ menu_level + 1 }}" inert>
            {{ menus.menu_items(item.below, attributes, menu_level + 1) }}
          </ul>
        {% endif %}
      </li>
    {% endif %}
  {% endfor %}
{% endmacro %}

templates/navigation.html.twig
{% set attributes = create_attribute() %}

<div {{ attributes.addClass('admin-toolbar-control-bar').setAttribute('data-drupal-admin-styles', '').setAttribute('data-offset-top', '') }}>
  <div class="admin-toolbar-control-bar__content">
    {% include '@navigation/toolbar-button.html.twig' with {
      attributes: create_attribute({'aria-expanded': 'false', 'aria-controls': 'admin-toolbar'}),
      icon: 'burger',
      text: 'Expand sidebar'|t,
      extra_classes: 'admin-toolbar-control-bar__burger',
    } only %}
  </div>
</div>

<aside
  class="admin-toolbar" id="admin-toolbar" data-drupal-admin-styles>
  {# This lil' div will get the Drupal.displace() attributes added to it via JS. #}
  <div class="admin-toolbar__displace-placeholder"></div>

  <div class="admin-toolbar__scroll-wrapper">
    {% set title_menu = 'admin-toolbar-title'|clean_unique_id %}

    {# @todo - We should get rid of this ID below. #}
    <nav id="menu-builder" class="admin-toolbar__content" aria-labelledby="{{ title_menu }}">
      <h3 id="{{ title_menu }}" class="visually-hidden">{{ 'Administrative toolbar content'|t }}</h3>
      {# @todo - Needs to be placed here so we can have the header footer on mobile. #}
      <div class="admin-toolbar__header">
        {% if not hide_logo %}
          <a class="admin-toolbar__logo" href="{{ path('<front>') }}">
            {% if logo_path %}
              <img alt="{{ 'Navigation logo'|t }}" src="{{ file_url(logo_path) }}" loading="eager" width="{{ logo_width|default(40) }}" height="{{ logo_height|default(40) }}">
            {% else %}
              {% include '@navigation/logo.svg.twig' with {
                label: 'Navigation logo'|t
              } only %}
            {% endif %}
          </a>
        {% endif %}
        {% include '@navigation/toolbar-button.html.twig' with {
          attributes: create_attribute({ 'data-toolbar-back-control': true, 'tabindex': '-1' }),
          extra_classes: 'admin-toolbar__back-button',
          icon: 'back',
          text: 'Back'|t,
        } only %}
        {% include '@navigation/toolbar-button.html.twig' with {
          attributes: create_attribute({ 'aria-controls': 'admin-toolbar', 'tabindex': '-1' }),
          extra_classes: 'admin-toolbar__close-button',
          icon: 'cross',
          label_classes: 'visually-hidden',
          text: 'Collapse sidebar'|t,
        } only %}
      </div>

      {{ menu_content }}
    </nav>

    {% set title_menu_footer = 'admin-toolbar-footer'|clean_unique_id %}
    <nav id="menu-footer" class="admin-toolbar__footer" aria-labelledby="{{ title_menu_footer }}">
      <h3 id="{{ title_menu_footer }}" class="visually-hidden">{{ 'Administrative toolbar footer'|t }}</h3>
      {{ menu_footer }}
      <button aria-controls="admin-toolbar" class="admin-toolbar__expand-button">
        <span class="visually-hidden" data-text>{{ 'Collapse sidebar'|t }}</span>
      </button>
    </nav>
  </div>
</aside>
<div class="admin-toolbar-overlay" aria-controls="admin-toolbar"></div>
<script>
  if (localStorage.getItem('Drupal.navigation.sidebarExpanded') !== 'false' && (window.matchMedia('(min-width: 1024px)').matches)) {
    document.documentElement.setAttribute('data-admin-toolbar', 'expanded');
  }
</script>

templates/toolbar-button.html.twig
{# Extra classes variable added to be sure that modifiers will
appear after main classes #}
{%
  set classes = [
    'toolbar-button',
    icon ? 'toolbar-button--icon--' ~ icon : '',
    extra_classes,
  ]
%}
<{{html_tag|default('button')}}{{ attributes.addClass(classes) }} data-index-text="{{ text|first|lower }}">
  {% if avatar %}
    <span class="toolbar-button__avatar">{{~ avatar ~}}</span>
  {% endif %}
  {% if action %}
    <span data-toolbar-action class="visually-hidden">{{ 'Extend'|t }}</span>
  {% endif %}
  {% block content %}
    {% if text %}
      <span class="toolbar-button__label {{ label_classes }}" data-text>{{~ text ~}}</span>
    {% endif %}
  {% endblock %}

  {# Element that improves sub-menu UX by implementing the Safe Triangle strategy.
More info at https://www.smashingmagazine.com/2023/08/better-context-menus-safe-triangles #}
  {% if has_safe_triangle %}
    <div data-toolbar-popover-safe-triangle></div>
  {% endif %}

</{{html_tag|default('button')}}>

templates/top-bar-local-task.html.twig
{#
/**
 * @file
 * Default theme implementation for a single navigation top bar local task.
 *
 * Available variables:
 * - link: Link render element.
 */
#}
<li class="toolbar-dropdown__item">
  {{ link|add_class('toolbar-dropdown__link') }}
</li>

templates/top-bar-local-tasks.html.twig
{#
/**
 * @file
 * Default theme implementation for navigation top bar local tasks.
 *
 * Available variables:
 * - local_tasks: Array of local tasks for the current route.
 */
#}
{% set dropdown_id = 'admin-local-tasks'|clean_unique_id %}
{% include '@navigation/toolbar-button.html.twig' with {
  attributes: create_attribute(
    {
      'aria-expanded': 'false',
      'aria-controls': dropdown_id,
      'data-drupal-dropdown': 'true'
    }
  ),
  text: 'More actions'|t,
  extra_classes: 'toolbar-button--expand--down toolbar-button--weight--400 toolbar-button--tertiary--expanded toolbar-button--actions',
} only %}
<div class="toolbar-dropdown__menu" id={{ dropdown_id }}>
  <ul class="toolbar-dropdown__list">
    {% for local_task in local_tasks %}
      {{ local_task }}
    {% endfor %}
  </ul>
</div>

templates/top-bar.html.twig
{#
/**
 * @file
 * Default theme implementation for the navigation top bar.
 *
 * Available variables:
 * - local_tasks: The local tasks for the current route.
 *
 * @ingroup themeable
 */
#}
{% set attributes = create_attribute() %}
{% if local_tasks %}
  {% set attributes = attributes.setAttribute('data-offset-top', '') %}
  <div {{ attributes.addClass('top-bar').setAttribute('data-drupal-admin-styles', '') }}>
    <div class="top-bar__content">
      {{ local_tasks }}
    </div>
  </div>
{% endif %}